---
name: Bot-MetaSyntactic
version: 0.0301
author:
  - 'Sébastien Aperghis-Tramoni <sebastien@aperghis.net>'
abstract: IRC frontend to Acme::MetaSyntactic
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Acme::MetaSyntactic: 0.70
  Bot::BasicBot: 0.12
build_requires:
  Test::More: 0
provides:
  Bot::MetaSyntactic:
    file: lib/Bot/MetaSyntactic.pm
    version: 0.0301
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
