---
name: Bot-MetaSyntactic
version: 0.02
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: IRC frontend to Acme::MetaSyntactic
license: perl
requires:
  Acme::MetaSyntactic: 0.12
  Test::More: 0
provides:
  Bot::MetaSyntactic:
    file: lib/Bot/MetaSyntactic.pm
    version: 0.02
generated_by: Module::Build version 0.2608
